service: Examples-Lambda-Functions-NodeJS
frameworkVersion: "4"
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  pizza_restaurant:
    handler: src/functions/pizza-restaurant/pizza-restaurant.pizza_restaurant
    events:
      - httpApi:
          path: /
          method: get